### ISSUE TITLE
NPX errors

### ISSUE THREAD

**Issue by idrtabd** [grand-stack/grand-stack-starter#136]
Works with Yarn, but fails with npx after I select API only.

PS c:\**********\dev\grandstack> npx create-grandstack-app testGraph3
? Please choose which project template to use API-Only
? Install dependencies? Yes
? Initialize a git repository? No
? Now let's configure your GraphQL API to connect to Neo4j. If you don't have a Neo4j instance you can create one for free in the cloud at https://neo4j.com/sandbox

Hit <Return> When you are ready.
? Alright, Enter the connection string for Neo4j bolt://localhost:7687
? Use an encrypted connection for Neo4j? (Select "No" for Neo4j Sandbox) No
? Enter the Neo4j user neo4j
? Enter the password for this user **************
Initializing Project...
  > Create GRANDstack App
    √ Creating directory 'c:\**********\dev\grandstack\testGraph3'
    √ Downloading latest release
    √ Extracting latest release
    √ Creating Local env file with configuration options...
    × Creating scripts configuration...
      → EEXIST: file already exists, mkdir 'c:\**********\dev\grandstack\testGraph3\scripts\config'
      Removing unused templates:
       ✔ web-angular
       ✔ mobile_client_flutter
    Installing Packages with yarn
node:fs:1010
  handleErrorFromBinding(ctx);
  ^

Error: EEXIST: file already exists, mkdir 'c:\**********\dev\grandstack\testGraph3\scripts\config'
    at Object.mkdirSync (node:fs:1010:3)
    at writeConfigJson (C:\Users\c:\**********\AppData\Local\npm-cache\_npx\f4182dbe734d24a0\node_modules\create-grandstack-app\tils\file.js:203:17)
    at C:\Users\c:\**********\AppData\Local\npm-cache\_npx\f4182dbe734d24a0\node_modules\listr\lib\task.js:167:30 {
  errno: -4075,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: 'C:\\Users\\c:\**********\\Documents\\dev\\grandstack\\testGraph3\\scripts\\config',
  context: [Object: null prototype] {}
}
npm ERR! code 1
npm ERR! path c:\**********\dev\grandstack
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-grandstack-app testGraph3

**Comment by idrtabd** [comment]
switched to npm, latest build appears to be fine
