### ISSUE TITLE
After the update to neo4j-graphql to 2.0 UI is broken

### ISSUE THREAD

**Issue by erichulser** [grand-stack/grand-stack-starter#14]
Here's the error:

```
{
   "errors":[
      {
         "message":"Cannot query field \"users\" on type \"Query\". Did you mean \"User\" or \"Business\"?",
         "locations":[
            {
               "line":2,
               "column":3
            }
         ],
         "extensions":{
            "code":"GRAPHQL_VALIDATION_FAILED",
            "exception":{
               "stacktrace":[
                  "Cannot query field \"users\" on type \"Query\". Did you mean \"User\" or \"Business\"?",
                  "",
                  "GraphQL request (2:3)",
                  "1: query usersPaginateQuery($first: Int, $offset: Int, $orderBy: _UserOrdering) {",
                  "2:   users(first: $first, offset: $offset, orderBy: $orderBy) {",
                  "     ^",
                  "3:     id",
                  "",
                  "    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:65:31)",
                  "    at Object.enter (/app/node_modules/graphql/language/visitor.js:324:29)",
                  "    at Object.enter (/app/node_modules/graphql/language/visitor.js:366:25)",
                  "    at visit (/app/node_modules/graphql/language/visitor.js:254:26)",
                  "    at visitUsingRules (/app/node_modules/graphql/validation/validate.js:74:22)",
                  "    at Object.validate (/app/node_modules/graphql/validation/validate.js:59:10)",
                  "    at Promise.resolve.then (/app/node_modules/apollo-server-core/src/runQuery.ts:188:30)",
                  "    at process._tickCallback (internal/process/next_tick.js:68:7)"
               ]
            }
         }
      }
   ]
}
```

**Comment by johnymontana** [comment]
Thanks for reporting @erichulser. This should be fixed by b189cb8c2abe31eec4479e779d308faa2f129208
