### ISSUE TITLE
Error running npx create-grandstack-app related to failed "Creating scripts configuration..."

### ISSUE THREAD

**Issue by cramatt** [grand-stack/grand-stack-starter#145]
Running `npx create-grandstack-app test-app` I get the following error.  I end up with a project that runs successfully, BUT it still has all the unused templates included. Looks like the process fails at the error, but the logging continues as if it were successful. 

Inside config directory I have a single file called `index.json` which contains the following: 

```
{ "templateFileName": "web-react", "templateName": "React" }
```

Here is the error: 

Maybe related to #136, #121

```
mmiller$ npx create-grandstack-app test-2
? Please choose which project template to use React-TS
? Install dependencies? No
? Initialize a git repository? No
? Now let's configure your GraphQL API to connect to Neo4j. If you don't have a Neo4j instance you can create one f
or free in the cloud at https://neo4j.com/sandbox

Hit <Return> When you are ready.
? Alright, Enter the connection string for Neo4j bolt://localhost:7687
? Use an encrypted connection for Neo4j? (Select "No" for Neo4j Sandbox) No
? Enter the Neo4j user neo4j
? Enter the password for this user letmein
Initializing Project...
  ❯ Create GRANDstack App
    ✔ Creating directory '/Users/mmiller/Sites/test-app'
    ✔ Downloading latest release
    ✔ Extracting latest release
    ✔ Creating Local env file with configuration options...
    ✖ Creating scripts configuration...
      → EEXIST: file already exists, mkdir '/Users/mmiller/Sites/test-app/scripts/config'
      Removing unused templates:
       ✔ web-react
       ✔ web-angular
       ✔ mobile_client_flutter
    Installing Packages with yarn
(node:10185) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/Users/mmiller/Sites/test-app/scripts/config'
    at Object.mkdirSync (fs.js:921:3)
    at writeConfigJson (/Users/mmiller/.config/yarn/global/node_modules/create-grandstack-app/dist/utils/file.js:110:15)
    at Task.task (/Users/mmiller/.config/yarn/global/node_modules/create-grandstack-app/dist/utils/file.js:203:17)
    at /Users/mmiller/.config/yarn/global/node_modules/listr/lib/task.js:167:30
(node:10185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10185) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here is my yarn version

```
yarn --version
1.22.4
```

Which IS out of date, I will try updating it now...

**Comment by cramatt** [comment]
Tried upgrading yarn, no luck.

Tried running the yarn command instead of npx, **success**! 

`yarn create grandstack-app` works, suggesting there is still a bug with the script?
