### ISSUE TITLE
Unable to user custom scalar with this starter

### ISSUE THREAD

**Issue by grw300** [grand-stack/grand-stack-starter#15]
I'm following [the documentation on custom scalars from packages](https://www.apollographql.com/docs/graphql-tools/scalars.html#Using-a-package) and trying to add the `JSON` scalar to the grand-stack-starter. I am getting an error whenever I try to start the api:

```
Error: Type "JSON" not found in document.
    at ASTDefinitionBuilder._resolveType (/app/node_modules/graphql/utilities/buildASTSchema.js:134:11)
```

The only changes I made to the starter are those outlined in the docs: added a scalar `JSON` to the schema and a new resolver:

schema.graphql
```javascript
scalar JSON

type Foo {
  aField: JSON
}

type User {
  id: ID!
  name: String
  friends: [User] @relation(name: "FRIENDS", direction: "BOTH")
  reviews: [Review] @relation(name: "WROTE", direction: "OUT")
  avgStars: Float @cypher(statement: "MATCH (this)-[:WROTE]->(r:Review) RETURN toFloat(avg(r.stars))")
  numReviews: Int @cypher(statement: "MATCH (this)-[:WROTE]->(r:Review) RETURN COUNT(r)")
}

type Business {
  id: ID!
  name: String
  address: String
  city: String
  state: String
  reviews: [Review] @relation(name: "REVIEWS", direction: "IN")
  categories: [Category] @relation(name: "IN_CATEGORY", direction: "OUT")
}

type Review {
  id: ID!
  stars: Int
  text: String
  business: Business @relation(name: "REVIEWS", direction: "OUT")
  user: User @relation(name: "WROTE", direction: "IN")
}

type Category {
  name: ID!
  businesses: [Business] @relation(name: "IN_CATEGORY", direction: "IN")
}

type Query {
    usersBySubstring(substring: String, first: Int = 10, offset: Int = 0): [User] @cypher(statement: "MATCH (u:User) WHERE u.name CONTAINS $substring RETURN u")
}
```

graphql-schema.js
```javascript
import { neo4jgraphql } from "neo4j-graphql-js";
import GraphQLJSON from 'graphql-type-json';
import fs from "fs";
import path from "path";

export const typeDefs = fs
    .readFileSync(
        process.env.GRAPHQL_SCHEMA || path.join(__dirname, "schema.graphql")
    )
    .toString("utf-8");

export const resolvers = {
    JSON: GraphQLJSON,
    Query: {
        usersBySubstring: neo4jgraphql
    }
};
```

What am I doing wrong here?

**Comment by JohnathanMaravilla** [comment]
I'm also having the same issue. When using any of the 'Custom scalars' examples provided in Apollo's [Graphql Tools docs](https://www.apollographql.com/docs/graphql-tools/scalars.html#custom-scalars), the Apollo Server crashes with a 

> Type "MyCustomScalar" not found in document

 error (or similar):

```
[nodemon] starting `babel-node src/index.js`
/Users/myUser/GRAND/api/node_modules/graphql/utilities/buildASTSchema.js:134
    throw new Error('Type "' + typeRef.name.value + '" not found in document.');
    ^

Error: Type "MyCustomScalar" not found in document.
    at ASTDefinitionBuilder._resolveType (/Users/myUser/GRAND/api/node_modules/graphql/utilities/buildASTSchema.js:134:11)
    at ASTDefinitionBuilder.buildType (/Users/myUser/GRAND/api/node_modules/graphql/utilities/buildASTSchema.js:218:79)
    at ASTDefinitionBuilder._buildWrappedType (/Users/myUser/GRAND/api/node_modules/graphql/utilities/buildASTSchema.js:227:24)
    at ASTDefinitionBuilder.buildField (/Users/myUser/GRAND/api/node_modules/graphql/utilities/buildASTSchema.js:248:18)
    at /Users/myUser/GRAND/api/node_modules/graphql/utilities/buildASTSchema.js:302:21
    at /Users/myUser/GRAND/api/node_modules/graphql/jsutils/keyValMap.js:28:31
    at Array.reduce (<anonymous>)
    at keyValMap (/Users/myUser/GRAND/api/node_modules/graphql/jsutils/keyValMap.js:27:15)
    at ASTDefinitionBuilder._makeFieldDefMap (/Users/myUser/GRAND/api/node_modules/graphql/utilities/buildASTSchema.js:299:49)
    at fields (/Users/myUser/GRAND/api/node_modules/graphql/utilities/buildASTSchema.js:284:23)
[nodemon] app crashed - waiting for file changes before starting...
```

I've been banging my head against this issue for about a week now. Any help would be appreciated.
