### ISSUE TITLE
Unknown function 'apoc.cypher.runFirstColumn'

### ISSUE THREAD

**Issue by jodok** [grand-stack/grand-stack-starter#4]
when i try to open http://localhost:3000 the UI shows only the message "Error".
When debugging the XHR i see the attached error message.
I seeded Neo4J with the sample data described in the README:

```
{
    "data": {
        "users": null
    },
    "errors": [
        {
            "message": "Unknown function 'apoc.cypher.runFirstColumn' (line 1, column 59 (offset: 58))\n\"MATCH (user:User {}) RETURN user { .id , .name ,avgStars: apoc.cypher.runFirstColumn(\"MATCH (this)-[:WROTE]->(r:Review) RETURN toFloat(avg(r.stars))\", {this: user}, false),numReviews: apoc.cypher.runFirstColumn(\"MATCH (this)-[:WROTE]->(r:Review) RETURN COUNT(r)\", {this: user}, false)} AS user SKIP 0 LIMIT 10\"\n                                                           ^",
            "locations": [],
            "path": [
                "users"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "code": "Neo.ClientError.Statement.SyntaxError",
                    "name": "Neo4jError",
                    "stacktrace": [
                        "Neo4jError: Unknown function 'apoc.cypher.runFirstColumn' (line 1, column 59 (offset: 58))",
                        "\"MATCH (user:User {}) RETURN user { .id , .name ,avgStars: apoc.cypher.runFirstColumn(\"MATCH (this)-[:WROTE]->(r:Review) RETURN toFloat(avg(r.stars))\", {this: user}, false),numReviews: apoc.cypher.runFirstColumn(\"MATCH (this)-[:WROTE]->(r:Review) RETURN COUNT(r)\", {this: user}, false)} AS user SKIP 0 LIMIT 10\"",
                        "                                                           ^",
                        "",
                        "    at captureStacktrace (/Users/jodok/sandbox/grand-stack-starter/api/node_modules/neo4j-driver/lib/v1/result.js:199:15)",
                        "    at new Result (/Users/jodok/sandbox/grand-stack-starter/api/node_modules/neo4j-driver/lib/v1/result.js:72:19)",
                        "    at Session._run (/Users/jodok/sandbox/grand-stack-starter/api/node_modules/neo4j-driver/lib/v1/session.js:116:14)",
                        "    at Session.run (/Users/jodok/sandbox/grand-stack-starter/api/node_modules/neo4j-driver/lib/v1/session.js:95:19)",
                        "    at _callee$ (/Users/jodok/sandbox/grand-stack-starter/api/node_modules/neo4j-graphql-js/dist/index.js:69:28)",
                        "    at tryCatch (/Users/jodok/sandbox/grand-stack-starter/api/node_modules/regenerator-runtime/runtime.js:62:40)",
                        "    at Generator.invoke [as _invoke] (/Users/jodok/sandbox/grand-stack-starter/api/node_modules/regenerator-runtime/runtime.js:296:22)",
                        "    at Generator.prototype.(anonymous function) [as next] (/Users/jodok/sandbox/grand-stack-starter/api/node_modules/regenerator-runtime/runtime.js:114:21)",
                        "    at step (/Users/jodok/sandbox/grand-stack-starter/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)",
                        "    at /Users/jodok/sandbox/grand-stack-starter/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14"
                    ]
                }
            }
        }
    ]
}
```

**Comment by jexp** [comment]
I added the info to the readme.

**Comment by jodok** [comment]
thank you! worked

**Comment by Joshfindit** [comment]
I had a similar issue due to having an old crufty version of APOC installed, but just as a head's up: the README no longer mentions APOC
